[Variables]
;No fancy config window here!
;Change these manually, save and refresh the thing.


;You must enter the coordinates, get them here: https://www.latlong.net/
Latitude=40.7128
Longitude=74.0060

IconStyle=Sun & Moon

;0 Enables automatic changing, 1 Disables it.
SunriseSunset=1

;Leaving this setting blank enables it, adding anything to it disables it
ChangeWallpaper=

WallpaperDark=#@#\Wallpaper\wall1.jpg
WallpaperLight=#@#\Wallpaper\wall0.jpg

;Supported options: RocketDock, NexusDock, ObjectDock or Disabled
ChangeDock=Disabled

;MUST Be exactly the name of the dock skins
DockDark=Big Sur Dark
DockLight=Big Sur

;Change to 0 to show debug info
ShowDebug=1

IconSize=64
ChangeWin10Mode=Change
